project_name: AWS Health Exporter
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/health-exporter/main.go
    binary: health-exporter
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'